SELECT *--COD_ARCHIVO
              FROM CFG_CLRLOAD
             ORDER BY COD_ARCHIVO;
             
INSERT into CFG_CLRLOAD (COD_ARCHIVO, COD_FORMATO, NOM_TABLA, DESC_TABLA) Values ('EX9001', 'EXMX', 'CLR_EX9001', 'NAIGUATA VISA');
INSERT into CFG_CLRLOAD (COD_ARCHIVO, COD_FORMATO, NOM_TABLA, DESC_TABLA) Values ('EX9010', 'EXMX', 'CLR_EX9010', 'NAIGUATA MASTER');

--delete from CFG_CLRLOAD  where COD_ARCHIVO='EX9001';
--delete from CFG_CLRLOAD  where COD_ARCHIVO='EX9010';