 SELECT *--C00LCSB
    --INTO vCSB_ENTADQ
    FROM ENTIDADES_PRICE
    
INSERT into ENTIDADES_PRICE (C00LCSB, C00LTIPO, C00NREDU, ES_ADQ, ES_EMITAR, ES_BCOPAG, RUC_ENTIDAD, COD_ENTADQ) Values ('9010', 2, 'Naiguata MasterCard', 'N', 'S','N','','XX');
INSERT into ENTIDADES_PRICE (C00LCSB, C00LTIPO, C00NREDU, ES_ADQ, ES_EMITAR, ES_BCOPAG, RUC_ENTIDAD, COD_ENTADQ) Values ('9001', 2, 'Naiguata VISA', 'N', 'S','N','','XX');
--update ENTIDADES_PRICE set C00NREDU='Naiguata VISA' where C00LCSB='9001';
--update ENTIDADES_PRICE set C00NREDU='Naiguata MasterCard' where C00LCSB='9010';

delete from ENTIDADES_PRICE  where C00LCSB='9001';
delete from ENTIDADES_PRICE  where C00LCSB='9010';